apiVersion: v1
kind: Service
metadata:
  name: prom-svc
  namespace: monitoring
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: 9090
spec:
  type: NodePort
  ports:
    - port: 8080
      name: prom-server-port
      targetPort: 9090
      nodePort: 8080
  selector:
    app: prometheus